site_name: Machine Learning Experiment Infrastructure
site_url: "https://mle-infrastructure.github.io/"
site_description: 'Remote ML experiments with Google Cloud Storage logging.'
site_author: Robert Tjarko Lange

repo_name: 'mle-infrastructure'
repo_url: 'https://github.com/mle-infrastructure'

copyright: Copyright &copy; 2021 - Robert Tjarko Lange

theme:
  name: material
  palette:
    - scheme: default
      primary: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.tabs
  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/favicon.ico
  logo: images/favicon.png

# plugins:
#  - mkdocs-jupyter

nav:
  - Home: index.md
  - Logging:
    - mle_logging.md
  - Hyperopt:
    - mle_hyperopt.md
  - Scheduler:
    - mle_scheduler.md
  - Monitor:
    - mle_monitor.md
  - Toolbox:
    - mle_toolbox/toolbox.md
    - mle_toolbox/subcommands.md
    - mle_toolbox/experiments.md
    - mle_toolbox/configuration.md
    #- mle_toolbox/getting_started.md

markdown_extensions:
  - codehilite:
      linenums: true
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mle-infrastructure
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/roberttlange
